import requests
from bs4 import BeautifulSoup
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# 🚨 SECURITY REMINDER: Reset your Client Secret on the Spotify Dashboard when you are done!
YOUR_APP_CLIENT_ID = ""
YOUR_APP_CLIENT_SECRET = ""
REDIRECT_URI = "https://developer.spotify.com/dashboard"

# 1. Authenticate with the required scope
sp = spotipy.Spotify(
    auth_manager=SpotifyOAuth(
        scope="playlist-modify-private",
        redirect_uri=REDIRECT_URI,
        client_id=YOUR_APP_CLIENT_ID,
        client_secret=YOUR_APP_CLIENT_SECRET,
        show_dialog=True,
        cache_path="token.txt"
    )
)

# Fetch ID dynamically to prevent 403 errors!
userID = sp.current_user()["id"]
print(f"Logged in as: {userID}")

date = "2026-01-10" # Changed to a past date so Billboard actually has data!

# ---------------------------------------------------------
# COMMENTED OUT SO IT STOPS MAKING EMPTY PLAYLISTS.
# IF YOU WANT A NEW PLAYLIST, UNCOMMENT THIS BLOCK.
# ---------------------------------------------------------
# playlist = sp.user_playlist_create(
#     user=userID, 
#     name=f"{date} Billboard 100", 
#     public=False,
#     description="My Musical Time Machine playlist generated by Python!"
# )
# playlist_id = playlist["id"]

# PASTE THE ID OF THE PLAYLIST YOU ALREADY CREATED HERE:
playlist_id = ""
# ---------------------------------------------------------

all_songs = []

# FIX: Added the date variable to the end of the URL!
URL = f"https://www.billboard.com/charts/hot-100/{date}"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
}
response = requests.get(URL, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")
songs = soup.find_all("li", class_="o-chart-results-list__item")

count = 1
for song in songs:
    title_element = song.find("h3", class_="c-title")
    if title_element:
        title = title_element.getText(strip=True)
        print(f"{count}. Title: {title}")
        count += 1
        all_songs.append(title)

print(f"\nTotal songs scraped from Billboard: {len(all_songs)}")

song_uris = []
print("Searching Spotify for songs... (This might take a minute)")

for song in all_songs:
    try:
        # Search Spotify for the specific track
        result = sp.search(q=f"track:{song}", type="track")
        
        # Dig into the JSON response to grab the URI of the very first result
        uri = result["tracks"]["items"][0]["uri"]
        song_uris.append(uri)
        
    except IndexError:
        print(f"Skipped: '{song}' doesn't exist on Spotify or wasn't found.")

print(f"\nFound {len(song_uris)} songs! Adding them to your playlist...")

# The magic command that pushes the whole list of URIs into your empty playlist
sp.playlist_add_items(playlist_id=playlist_id, items=song_uris)

print("Playlist complete! Go check your Spotify app again! 🎧")